SELECT *
FROM PRODUCT;

SELECT P_CODE, P_QOH,
FROM PRODUCT;

SELECT P_CODE, P_DESCRIPT, P_PRICE
FROM PRODUCT
WHERE P_PRICE <50
;

SELECT *
FROM `PRODUCT` 
WHERE P_PRICE >= 100
AND
P_QOH < 10

SELECT * FROM `PRODUCT`
WHERE P_CODE = '13-Q2/P2'
OR
P_CODE = '2232/QTY'
OR
P_CODE = '23114-AA'

SELECT * FROM `PRODUCT`
WHERE P_CODE IN ('13-Q2/P2', '2232/QTY','23114-AA')

SELECT * FROM `PRODUCT`
WHERE P_CODE NOT IN ('13-Q2/P2', '2232/QTY','23114-AA')

SELECT * FROM `PRODUCT`
WHERE P_CODE NOT IN ('WR3/TT3', '54778-2T')

SELECT * FROM `PRODUCT`
WHERE 
P_CODE <> 'WR3/TT3'
AND
P_CODE <> '54778-2T'

SELECT P_DESCRIPT 
FROM PRODUCT 
WHERE P_DESCRIPT LIKE 'B%'

SELECT P_DESCRIPT 
FROM PRODUCT 
WHERE P_DESCRIPT LIKE '%JIGSAW%'

SELECT P_CODE, P_DESCRIPT
FROM PRODUCT 
WHERE P_CODE LIKE '__1%'

SELECT P_CODE, P_DESCRIPT
FROM PRODUCT 
WHERE P_DESCRIPT LIKE '%SAW%' 

SELECT P_CODE, P_DESCRIPT
FROM PRODUCT 
WHERE P_DESCRIPT LIKE '%SCREW%'

SELECT P_CODE, P_DESCRIPT
FROM PRODUCT 
WHERE P_DESCRIPT NOT LIKE '%SAW%'
AND
P_DESCRIPT NOT LIKE '%SCREW%' ; 

SELECT * 
FROM PRODUCT
WHERE P_PRICE >= 30
ORDER BY V_CODE DESC, P_DESCRIPT ASC

SELECT P_CODE, P_DESCRIPT, P_PRICE, P_QOH, P_PRICE*P_QOH AS INV_VALUE
FROM PRODUCT;

SELECT COUNT(*)
FROM PRODUCT

SELECT COUNT(P_CODE) AS NUM_PRODUCT
FROM PRODUCT

SELECT COUNT(*) AS EXP_PRODUCT 
FROM PRODUCT
WHERE P_PRICE > 100;

SELECT AVG(P_PRICE) AS PRICE_AVG
FROM PRODUCT 

SELECT AVG (P_PRICE*P_QOH) AS AVG_INV_VALUE
FROM PRODUCT 
